### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by steveyken** [timurb/check-mk-sidekiq#1]
Thanks for this plugin - exactly what I was looking for and great that it's so easy to extend for other checks.

I've got it installed and running on a host and the output is in the CheckMK datastream (checked using telnet). The step I'm missing is that it's not automatically picked up in services when I do an auto inventory inside CheckMK WATO... what step am I missing?

**Comment by timurb** [comment]
Hi Steve,

I'm afraid I can't help much here -- the CheckMK installation and configuration itself was handled by our customer's team and I don't have much vision into how that was enabled.
If you have some info on how to handle that -- please share and I'll update the README (pull requests are of course welcome too).

**Comment by steveyken** [comment]
Thanks, I appreciate this request isn't really an issue with the plugin.
Feel free to close and I'll post here if I figure it out.
